### ISSUE TITLE
build: update scripts

### ISSUE THREAD

**Issue by jer3m01** [kobaltedev/kobalte#318]
- [x] Update to prettier v4 #323
- [x] Add biome for supported file types #323
- [x] Replace Eslint with Biome #325 
- [x] Remove git hooks #329
- [x] Add workflow checks #328
